version: "3.7"

networks:
  user:
    driver: bridge

services:
  app:
    container_name: user
    networks:
      - user
    ports:
      - 5000:5000
    depends_on:
      - postgre
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
  postgre:
    restart: always
    container_name: postgredb
    networks:
      - user
    expose:
      - 5432
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
    volumes:
      - type: volume
        source: postgredata
        target: /var/lib/postgresql/data

volumes:
  postgredata:
